### ISSUE TITLE
Error: undefined variable: s:resource_command_name

### ISSUE THREAD

**Issue by wbthomason** [yuki-yano/fzf-preview.vim#138]
First off, thanks for the useful plugin!

Since updating to the new `rplugin`-based version of the plugin, I've started getting some errors.

While running the `:Buffers` command from https://github.com/junegunn/fzf.vim (which I prefer because it selects the alt file first), I'm getting the following error:
```
Error detected while processing function fzf_preview#remote#window#set_fzf_last_query:
line 5:
E121: Undefined variable: s:resource_command_name
Error detected while processing function fzf_preview#remote#window#set_fzf_last_query:
line 5:
E116: Invalid arguments for function FzfPreviewDispatchResumeQuery
```

I'm also seeing `UpdateRemotePlugins` only _sometimes_ correctly find the commands this plugin defines (i.e. it always finds the plugin, but sometimes defines it as an empty plugin?), but I suspect that's a problem with Neovim/the Node host rather than this plugin.

**Comment by wbthomason** [comment]
Slight update: the trouble with `UpdateRemotePlugins` seems related after all. When I've gotten that to run successfully, I don't see the other errors. I'm not sure why it only sometimes runs successfully, though.

**Comment by yuki-yano** [comment]
Fixed from https://github.com/yuki-ycino/fzf-preview.vim/commit/5fadcd576219091790f141098560977ab4014a23

I believe the error should now stop occurring.
However, when executing a command other than fzf-preview.vim, I get an incorrect resume in There is still a bug in which it is saved.
I will consider a fix for this bug in the future.

**Comment by wbthomason** [comment]
It seems to be gone for me (and it seems like `UpdateRemotePlugins` is more consistently working for this plugin?)

Thank you!

**Comment by yuki-yano** [comment]
I just modified FzfPreviewBuffers to sort by mru.
Also, modified buffers are now marked with a +.
You can try it out if you want.

![スクリーンショット 2020-07-09 1 52 20](https://user-images.githubusercontent.com/5423775/86947561-e3368180-c186-11ea-87aa-b32fada160c6.png)

**Comment by wbthomason** [comment]
Thanks! I'm unfortunately still having some issues with `UpdateRemotePlugins` not always finding the commands for this plugin, but I suspect that's an issue on my end.
